version: "3.9"

services:
  war-game:
    container_name: war-game
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}:/var/www:delegated
      - ~/.composer/auth.json:/root/.composer/auth.json:ro
